[package]
name = "skyseeker-parse"
version = "0.1.0"
edition = "2024"

[dependencies]
skyseeker-core = { workspace = true }
anyhow = "1.0.100"
serde = { workspace = true }
serde_json = { workspace = true }