[workspace]
members = ["app", "core", "parse"]
resolver = "3"

[workspace.dependencies]
skyseeker-core = { path = "core" }
bincode = "2.0.1"
chrono = "0.4.42"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
zstd = "0.13.3"