[package]
name = "skyseeker-core"
version = "0.1.0"
edition = "2024"

[features]
default = []

[dependencies]
astro = "2.0.0"
bincode = { workspace = true }
chrono = { workspace = true, optional = true }
sofars = "0.3.3"
thiserror = "2.0.17"
zstd = { workspace = true }